development:
  adapter: postgresql
  encoding: unicode
  database: myrestaurant
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: myrestaurant
  pool: 5
  username: postgres
  password: root
