
development:
  adapter: postgresql
  encoding: unicode
  database: myrestaurant
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: myrestaurant_test
  pool: 5
  username: postgres
  password: root
